<template >
  <TMSMGT_QYVue
    ref="quYu_Target"
    id_AA="YSQ"
    class="yunshu"
    title="运输区"
    title1="运输区"
    back_color="#FFC080"
    q_width="100px"
    q_height="600px"
    name_isvisable:true
    :allow_Place="true"
    :dataList="mainData.blocks['Table0']"
    v-if="loaded"
    @handleMouseEnter="handleMouseEnter"
    @handleMouseLeave1="handleMouseLeave"
    @DragEnd="DragEnd"
    @DragStart="DragStart"
  />
  <el-select
    placeholder="更多操作"
    class="button_select"
    effect="dark"
    style="background-color: #409eff"
  >
    <el-option
      class="add_tank"
      label="添加罐"
      value="添加罐"
      @click="click_add"
      :style="{ cursor: 'pointer' }"
    ></el-option>
    <el-option
      class="refresh"
      label="刷新"
      value="刷新"
      @click="click_refresh"
      :style="{ cursor: 'pointer' }"
    ></el-option>
    <el-option
      class="show_tank"
      label="全部罐信息"
      value="全部罐信息"
      @click="click_skip"
      :style="{ cursor: 'pointer' }"
    ></el-option>

    <el-option
      class="con_plan"
      label="维修记录"
      value="维修记录"
      @click="click_skip1"
      :style="{ cursor: 'pointer' }"
    ></el-option>
    <el-option
      class="con_plan"
      label="烘烤记录"
      value="烘烤记录"
      @click="click_skip2"
      :style="{ cursor: 'pointer' }"
    ></el-option>
  </el-select>
  <el-card class="card_show" shadow="always" body-style="align-items: center;">
    {{ targetCell_Now }}
  </el-card>
  <div
    class="root"
    ref="root"
    @wheel="handleZoom"
    @mousedown="handleMouseDown"
    @mousemove="handleMouseMove"
    @mouseup="handleMouseUp"
   
  >
    <div class="cantainer">
      <el-divider class="line-L" content-position="left">L</el-divider>
      <div class="weizhi_ch" id="zhakua">渣跨</div>
      <el-divider class="line-K" content-position="left">K</el-divider>
      <div class="weizhi_ch" id="dianlukua">电炉跨</div>
      <el-divider class="line-J" content-position="left">J</el-divider>
      <div class="weizhi_ch" id="jialiaokua">加料跨</div>
      <el-divider class="line-H" content-position="left">H</el-divider>
      <div class="weizhi_ch" id="luzikua">炉子跨</div>
      <el-divider class="line-G" content-position="left">G</el-divider>
      <div class="weizhi_ch" id="jieshoukua">钢水接受跨</div>
      <el-divider class="line-F" content-position="left">F</el-divider>
      <div class="backGround">
        <div class="zhanban">
          <div class="item">
            <div class="画面说明">>>> 画面说明</div>
            <div>
              <div class="xianshi_title">
                <div>当前罐数量</div>
                <div id="label_count">{{ label_count }}</div>
              </div>
              <div class="xianshi_title">
                <div>管理范围</div>
                <div>全局</div>
              </div>
            </div>
          </div>
          <div class="seqian">
            <div class="colorqian">
              <input type="color" value="#B0E0E6" disabled="true"/>
              <label>冷修区域</label>
            </div>
            <div class="colorqian">
              <input type="color" value="#DDA0DD" disabled="true"/>
              <label>热修区域</label>
            </div>
            <div class="colorqian">
              <input type="color" value="#FFFF00" disabled="true"/>
              <label>可直接分配区域</label>
            </div>
            <div class="colorqian">
              <input type="color" value="#98FB98" disabled="true"/>
              <label>在线不能分配区域</label>
            </div>
            <div class="colorqian">
              <input type="color" value="#FFC080" disabled="true"/>
              <label>位置区域</label>
            </div>
          </div>
        </div>
             <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="Z4_1"
          class="Z4_1"
          title="中频炉4"
          title1="Z4_1"
          back_color="#FFFF00"
          q_width="100px"
          q_height="80px"
          name_isvisable:true
          :allow_Place="true"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="Z4_2"
          class="Z4_2"
          title="-"
          title1="Z4_2"
          back_color="#FFFF00"
          q_width="100px"
          q_height="80px"
          name_isvisable:true
          :allow_Place="true"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="Z3_1"
          class="Z3_1"
          title="中频炉3"
          title1="Z3_1"
          back_color="#FFFF00"
          q_width="100px"
          q_height="80px"
          name_isvisable:true
          :allow_Place="true"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="Z3_2"
          class="Z3_2"
          title="-"
          title1="Z3_2"
          back_color="#FFFF00"
          q_width="100px"
          q_height="80px"
          name_isvisable:true
          :allow_Place="true"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="Z2_1"
          class="Z2_1"
          title="中频炉2"
          title1="Z2_1"
          back_color="#FFFF00"
          q_width="100px"
          q_height="80px"
          name_isvisable:true
          :allow_Place="true"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="Z2_2"
          class="Z2_2"
          title="-"
          title1="Z2_2"
          back_color="#FFFF00"
          q_width="100px"
          q_height="80px"
          name_isvisable:true
          :allow_Place="true"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="Z1_1"
          class="Z1_1"
          title="中频炉1"
          title1="Z1_1"
          back_color="#FFFF00"
          q_width="100px"
          q_height="80px"
          name_isvisable:true
          :allow_Place="true"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="Z1_2"
          class="Z1_2"
          title="-"
          title1="Z1_2"
          back_color="#FFFF00"
          q_width="100px"
          q_height="80px"
          name_isvisable:true
          :allow_Place="true"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="HMH2"
          class="HMH2"
          title="HMH2"
          title1="HMH2"
          back_color="#98FB98"
          q_width="140px"
          q_height="80px"
          name_isvisable:true
          :allow_Place="false"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="HMH1"
          class="HMH1"
          title="HMH1"
          title1="HMH1"
          back_color="#98FB98"
          q_width="140px"
          q_height="80px"
          name_isvisable:true
          :allow_Place="false"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="TSWT"
          class="TS_wait"
          title=""
          title1="铁水罐等待区"
          back_color="#FFFF00"
          q_width="290px"
          q_height="65px"
          :allow_Place="true"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="EAF2"
          class="EAF2"
          title="EAF2"
          title1="EAF2"
          back_color="#98FB98"
          q_width="140px"
          q_height="80px"
          name_isvisable:true
          :allow_Place="false"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="EAF1"
          class="EAF1"
          title="EAF1"
          title1="EAF1"
          back_color="#98FB98"
          q_width="140px"
          q_height="80px"
          name_isvisable:true
          :allow_Place="false"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="YRWT"
          class="YR_wait"
          title=""
          title1="预熔等待区"
          back_color="#FFFF00"
          q_width="290px"
          q_height="65px"
          :allow_Place="true"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <!--DES-->
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="DES3"
          class="DES3"
          title="DES3"
          title1="DES3"
          back_color="#98FB98"
          q_width="140px"
          q_height="80px"
          name_isvisable:true
          :allow_Place="false"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="DES2"
          class="DES2"
          title="DES2"
          title1="DES2"
          back_color="#98FB98"
          q_width="140px"
          q_height="80px"
          name_isvisable:true
          :allow_Place="false"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="DES1"
          class="DES1"
          title="DES1"
          title1="DES1"
          back_color="#98FB98"
          q_width="140px"
          q_height="80px"
          name_isvisable:true
          :allow_Place="false"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <!--BOF-->
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="BOF0"
          class="BOF0"
          title="BOF0"
          title1="BOF0"
          back_color="#FFFF00"
          q_width="140px"
          q_height="80px"
          name_isvisable:true
          :allow_Place="true"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="BOF2"
          class="BOF2"
          title="BOF2"
          title1="BOF2"
          back_color="#FFFF00"
          q_width="140px"
          q_height="80px"
          name_isvisable:true
          :allow_Place="true"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="BOF1"
          class="BOF1"
          title="BOF1"
          title1="BOF1"
          back_color="#FFFF00"
          q_width="140px"
          q_height="80px"
          name_isvisable:true
          :allow_Place="true"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <!--AOD-->
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="AOD2"
          class="AOD2"
          title="AOD2"
          title1="AOD2"
          back_color="#FFFF00"
          q_width="140px"
          q_height="80px"
          name_isvisable:true
          :allow_Place="true"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="AOD1"
          class="AOD1"
          title="AOD1"
          title1="AOD1"
          back_color="#FFFF00"
          q_width="140px"
          q_height="80px"
          name_isvisable:true
          :allow_Place="true"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="AOD0"
          class="AOD0"
          title="AOD0"
          title1="AOD0"
          back_color="#FFFF00"
          q_width="140px"
          q_height="80px"
          name_isvisable:true
          :allow_Place="true"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <!--VOD-->
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="VOD2"
          class="VOD2"
          title="VOD2"
          title1="VOD2"
          back_color="#98FB98"
          q_width="140px"
          q_height="80px"
          name_isvisable:true
          :allow_Place="false"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="VOD1"
          class="VOD1"
          title="VOD1"
          title1="VOD1"
          back_color="#98FB98"
          q_width="140px"
          q_height="80px"
          name_isvisable:true
          :allow_Place="false"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <!--RH-->
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="RH2_2"
          class="RH2_2"
          title="RH2_2"
          title1="RH2_2"
          back_color="#98FB98"
          q_width="140px"
          q_height="80px"
          name_isvisable:true
          :allow_Place="false"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="RH2_1"
          class="RH2_1"
          title="RH2_1"
          title1="RH2_1"
          back_color="#98FB98"
          q_width="140px"
          q_height="80px"
          name_isvisable:true
          :allow_Place="false"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="RH1_2"
          class="RH1_2"
          title="RH1_2"
          title1="RH1_2"
          back_color="#98FB98"
          q_width="140px"
          q_height="80px"
          name_isvisable:true
          :allow_Place="false"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="RH1_1"
          class="RH1_1"
          title="RH1_1"
          title1="RH1_1"
          back_color="#98FB98"
          q_width="140px"
          q_height="80px"
          name_isvisable:true
          :allow_Place="false"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <!--LF-->
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="LF3_2"
          class="LF3_2"
          title="LF3_2"
          title1="LF3_2"
          back_color="#98FB98"
          q_width="140px"
          q_height="80px"
          name_isvisable:true
          :allow_Place="false"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="LF3_1"
          class="LF3_1"
          title="LF3_1"
          title1="LF3_1"
          back_color="#98FB98"
          q_width="140px"
          q_height="80px"
          name_isvisable:true
          :allow_Place="false"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="LF2_2"
          class="LF2_2"
          title="LF2_2"
          title1="LF2_2"
          back_color="#98FB98"
          q_width="140px"
          q_height="80px"
          name_isvisable:true
          :allow_Place="false"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="LF2_1"
          class="LF2_1"
          title="LF2_1"
          title1="LF2_1"
          back_color="#98FB98"
          q_width="140px"
          q_height="80px"
          name_isvisable:true
          :allow_Place="false"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="LF1_2"
          class="LF1_2"
          title="LF1_2"
          title1="LF1_2"
          back_color="#98FB98"
          q_width="140px"
          q_height="80px"
          name_isvisable:true
          :allow_Place="false"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="LF1_1"
          class="LF1_1"
          title="LF1_1"
          title1="LF1_1"
          back_color="#98FB98"
          q_width="140px"
          q_height="80px"
          name_isvisable:true
          :allow_Place="false"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <!--碳钢冷修区-->
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="TLX_2"
          class="TLX_2"
          title="碳钢冷修区"
          title1="已修区"
          back_color="#B6E3E8"
          q_width="300px"
          q_height="80px"
          name_isvisable:true
          :allow_Place="true"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="TLX_1"
          class="TLX_1"
          title="-"
          title1="待修区"
          back_color="#B6E3E8"
          q_width="300px"
          q_height="80px"
          name_isvisable:true
          :allow_Place="true"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <!--不锈钢冷修区-->
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="BLX_1"
          class="BLX_1"
          title="不锈钢冷修区"
          title1="待修区"
          back_color="#B6E3E8"
          q_width="300px"
          q_height="80px"
          name_isvisable:true
          :allow_Place="true"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="BLX_2"
          class="BLX_2"
          title="-"
          title1="已修区"
          back_color="#B6E3E8"
          q_width="300px"
          q_height="80px"
          name_isvisable:true
          :allow_Place="true"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <!--碳钢冷修烘烤区-->
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="TLK_2"
          class="TLK_2"
          title="碳钢冷修烘烤区"
          title1="烘烤区2"
          back_color="#DDA0DD"
          q_width="140px"
          q_height="80px"
          name_isvisable:true
          :allow_Place="true"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="TLK_1"
          class="TLK_1"
          title="-"
          title1="烘烤区1"
          back_color="#DDA0DD"
          q_width="140px"
          q_height="80px"
          name_isvisable:true
          :allow_Place="true"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <!--碳钢热修区-->
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="TRX_2"
          class="TRX_2"
          title="碳钢热修区"
          title1="热修区"
          back_color="#DDA0DD"
          q_width="140px"
          q_height="80px"
          name_isvisable:true
          :allow_Place="true"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="TRX_1"
          class="TRX_1"
          title="-"
          title1="检修区"
          back_color="#DDA0DD"
          q_width="140px"
          q_height="80px"
          name_isvisable:true
          :allow_Place="true"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <!--CCM-->
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="CM4_2"
          class="CM4_2"
          title="CCM4"
          title1="CCM4"
          back_color="#98FB98"
          q_width="100px"
          q_height="80px"
          name_isvisable:true
          :allow_Place="false"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="CM3_2"
          class="CM3_2"
          title="CCM3"
          title1="CCM3"
          back_color="#98FB98"
          q_width="100px"
          q_height="80px"
          name_isvisable:true
          :allow_Place="false"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="CM2_2"
          class="CM2_2"
          title="CCM2"
          title1="CCM2"
          back_color="#98FB98"
          q_width="100px"
          q_height="80px"
          name_isvisable:true
          :allow_Place="false"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="CM1_2"
          class="CM1_2"
          title="CCM1"
          title1="CCM1"
          back_color="#98FB98"
          q_width="100px"
          q_height="80px"
          name_isvisable:true
          :allow_Place="false"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="CM0_2"
          class="CM0_2"
          title="CCM0"
          title1="CCM0"
          back_color="#98FB98"
          q_width="100px"
          q_height="80px"
          name_isvisable:true
          :allow_Place="false"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="CM4_1"
          class="CM4_1"
          title=""
          title1=" "
          back_color="#FFFF00"
          q_width="100px"
          q_height="65px"
          name_isvisable:true
          :allow_Place="true"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="CM3_1"
          class="CM3_1"
          title=""
          title1="CCM3事故位"
          back_color="#FFFF00"
          q_width="100px"
          q_height="65px"
          name_isvisable:true
          :allow_Place="true"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="CM2_1"
          class="CM2_1"
          title=""
          title1="CCM2事故位"
          back_color="#FFFF00"
          q_width="100px"
          q_height="65px"
          name_isvisable:true
          :allow_Place="true"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="CM1_1"
          class="CM1_1"
          title=""
          title1="CCM1事故位"
          back_color="#FFFF00"
          q_width="100px"
          q_height="65px"
          name_isvisable:true
          :allow_Place="true"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="CM0_1"
          class="CM0_1"
          title=""
          title1=" "
          back_color="#FFFF00"
          q_width="100px"
          q_height="65px"
          name_isvisable:true
          :allow_Place="true"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <!--不锈钢热修区-->
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="BRX_2"
          class="BRX_2"
          title="不锈钢热修区"
          title1="热修区"
          back_color="#DDA0DD"
          q_width="140px"
          q_height="80px"
          name_isvisable:true
          :allow_Place="true"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="BRX_1"
          class="BRX_1"
          title="-"
          title1="检修区"
          back_color="#DDA0DD"
          q_width="140px"
          q_height="80px"
          name_isvisable:true
          :allow_Place="true"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <!--不锈钢冷修烘烤区-->
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="BLK_1"
          class="BLK_1"
          title="不锈钢冷修烘烤区"
          title1="烘烤区1"
          back_color="#DDA0DD"
          q_width="140px"
          q_height="80px"
          name_isvisable:true
          :allow_Place="true"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
        <TMSMGT_QYVue
          ref="quYu_Target"
          id_AA="BLK_2"
          class="BLK_2"
          title="-"
          title1="烘烤区2"
          back_color="#DDA0DD"
          q_width="140px"
          q_height="80px"
          name_isvisable:true
          :allow_Place="true"
          :dataList="mainData.blocks['Table0']"
          v-if="loaded"
          @handleMouseEnter="handleMouseEnter"
          @handleMouseLeave1="handleMouseLeave"
          @DragEnd="DragEnd"
          @DragStart="DragStart"
        />
      </div>
     
      <xr-ef-dialog
        v-model:visible="dialogVisible"
        :title="dialogFormName"
        height="80%"
        width="80%"
        @click-close-icon="xrEfDialogClose"
        :default-footer="false"
      >
        <TMSMGT_ADD
          :openInDialog="true"
          :parentInfo="'TMSMGT_ADD'"
          @getChildInfo="getChildInfo"
        ></TMSMGT_ADD>
      </xr-ef-dialog>
      <xr-ef-dialog
        v-model:visible="dialogVisible_H"
        :title="dialogFormName"
        height="80%"
        width="80%"
        @click-close-icon="xrEfDialogClose"
        :default-footer="false"
      >
        <TMSMGT_HANDLE
          :openInDialog="true"
          :parentInfo="'TMSMGT_HANDLE'"
          :old_posi="old_posi"
          :new_posi="new_posi"
          @getChildInfo="getChildInfo_H"
          @getChildprocess="getChildprocess"
        ></TMSMGT_HANDLE>
      </xr-ef-dialog>
    </div>
  </div>
</template>

<script lang="ts" src="./TMSMGT.ts"></script>

<style scoped>
@import "./TMSMGT.scss";
</style>
